### ISSUE TITLE
麦克风不能工作

### ISSUE THREAD

**Issue by RichardWei** [WingLim/Dell-Optiplex-5070mff-Hackintosh#1]
你好，使用了您的EFI文件，修改三码之后已经可以正常工作了，但是麦克风输入好像不行，试了好多layout-id，有什么解决办法吗？

**Comment by WingLim** [comment]
配置EFI的时候我也试过很多layout-id，ALC255声卡下，66是目前最完美的，但这个layout没有配置好麦克风输入，修正这个问题需要在66的基础上进行改进。

具体方式可以看这里：https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html

近期比较忙，没有时间去适配，你可以尝试一下，过段时间有空了我会尝试修复。

**Comment by RichardWei** [comment]
好的，谢谢，我有时间也来折腾一下这个，感谢，现在用也没什么问题。

**Comment by WingLim** [comment]
发布了v1.2.0，通过[ComboJack](https://github.com/hackintosh-stuff/ComboJack)来设置设备可以正常使用耳机的麦克风了，你可以试一试，看看有没有什么问题，我这边测试可以正常使用了。

**Comment by WingLim** [comment]
重写了一个 [MicFix](https://github.com/WingLim/MicFix) 可以自动修复麦克风，我这边测试是能正常使用了，如果还有其他问题，请反馈。

**Comment by WingLim** [comment]
现在可以通过 brew 来安装了

https://github.com/WingLim/MicFix#use-brewrecommend

```bash
brew tap winglim/taps
brew install micfix
brew services start micfix
```

**Comment by RichardWei** [comment]
好的，现在才看到，我晚上试一下
