### ISSUE TITLE
Final Cut Pro，iMovie 运行后不能退出 efi1.0.0

### ISSUE THREAD

**Issue by ps2zhuantou** [WingLim/Dell-Optiplex-5070mff-Hackintosh#4]
big sur 11.2.3 不能退出
catalina 10.7 没问题

**Comment by WingLim** [comment]
试了一下 iMovie 确实有这个问题，退出的时候未响应了，我找找是什么原因。

**Comment by WingLim** [comment]
v1.3.1 已经修复这个问题，或者你可以手动更改来修复这个问题：
删除 `DeviceProperties` -> `PciRoot(0x0)/Pci(0x2,0x0)` -> `AAPL,slot-name` 即可，如下图所示
![image](https://user-images.githubusercontent.com/6434137/118473880-08980280-b73d-11eb-9d99-6e4835e9607f.png)
猜测是添加了 slot-name 后 HEVC 无法正常工作导致的异常。

**Comment by ps2zhuantou** [comment]
给力，谢谢
