### ISSUE TITLE
missing reset nvram tool

### ISSUE THREAD

**Issue by ntvsp** [WingLim/Dell-Optiplex-5070mff-Hackintosh#5]
i not found rết nvram tool in opencore boot??? i need this pls add tool, thanks sir

**Comment by ntvsp** [comment]
what is loweset level isk is not ounted???

**Comment by WingLim** [comment]
I set OpenCore hide the auxiliary entry.
So you need to press `Space` when OpenCore show boot item.
Then the `Rest Nvram` will show up.

And the `loweset level isk is not ounted`?
Can you show me a screenshot?

**Comment by ntvsp** [comment]
pls help me thanks sir.
https://www.youtube.com/watch?v=Al9Frfl3f9c&t=2s

**Comment by WingLim** [comment]
I do a little research.
Booting stuck at `DOMOS has arrived` cause by SMC device.
The `VirtualSMC` will fix this, but I have config it.
So take a look at https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/boot.html

**Comment by WingLim** [comment]
So, have you solved it?

**Comment by ntvsp** [comment]
> So, have you solved it?

I have to use ubuntu, i quit. 
tks sir

**Comment by WingLim** [comment]
Alright.
